version: '3'
services:
  visualizador:
    image: dockersamples/visualizer
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
    - 8080:8080
    deploy:
      placement:
        constraints:
          - node.role == manager

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - internal

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - internal
      - producers

  nodejs-producer:
    image: luizkt/nodejs-producer-bf
    depends_on:
      - kafka
    ports:
      - 3000
    environment:
      KAFKA_CLIENT_ADDRESS: kafka:9092
    networks:
      - internal
      - producers

networks:
  internal:
    external: false
  producers:
    external: true
